name: Manual trigger
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Choose an environment"
                required: true
                default: "staging"
                type: choice
                options:
                    - staging
                    - production
                    


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy application
              run: echo "Manual trigger triggered successfully <3"